---
version: "3.7"
services:
  factorio:
    container_name: factorio
    hostname: factorio
    stdin_open: true
    tty: true
    build:
      context: ./
      args:
        VERSION: "1.0.0"
    environment:
      - SAVE=testo.zip
    ports:
      - "34197:34197/udp"
    volumes:
      - "/opt/factorio:/factorio"
